### ISSUE TITLE
Directory Browsing

### ISSUE THREAD

**Issue by tcmak** [nerds-odd-e/scrummaster-checklist#11]
I noticed that Directory Browsing is enabled for this website, e.g. http://www.scrummasterchecklist.org/pdf/

Is that any issue anyone want to fix?

**Comment by basvodde** [comment]
Please make a pull request :)

**Comment by SabotagePerformanceAppraisals** [comment]
I’m wondering whether this is actually a problem.  I kinda like directory browsing.  But if it’s bugging you.. sure.. fix it.

—mj
(Michael)

**Comment by SabotagePerformanceAppraisals** [comment]
Suggest closing this issue if no objections.  I don't see a security risk with directory browsing on a static site.
