### ISSUE TITLE
How can I contribute to translate in Thai?

### ISSUE THREAD

**Issue by nattyait** [nerds-odd-e/scrummaster-checklist#20]
Hi nerds,

I'm Natty. I'm using the ScrumMaster checklist for teaching. I think it's time to help on the contribution. How can I start helping on ScrumMaster checklist to Thai?

Best,
Natty

**Comment by SabotagePerformanceAppraisals** [comment]
Dear Natty,

We’d love to see a Thai version.  You can submit it with a git pull request, or email to us and we’ll do the git stuff.

—mj
(Michael)

**Comment by SabotagePerformanceAppraisals** [comment]
There is now a Thai version at http://scrummasterchecklist.org/pdf/ScrumMaster_Checklist_th.pdf .  Is it OK to close this issue now?
