### ISSUE TITLE
SSL certificate mismatch

### ISSUE THREAD

**Issue by SabotagePerformanceAppraisals** [nerds-odd-e/scrummaster-checklist#29]
When I trying to go to https://scrummasterchecklist.org I get this message:
`This server could not prove that it is scrummasterchecklist.org; its security certificate is from *.odd-e.com. This may be caused by a misconfiguration or an attacker intercepting your connection`

From the deploy file, it looks like this is being served from Linode www.odd-e.com.  I think it would not be possible to turn off https just for one domain name.  Since GitHub Pages now provides its own certificate, we could move the page there?

**Comment by basvodde** [comment]
Solved.
