### ISSUE TITLE
Website does't have latest PDF links

### ISSUE THREAD

**Issue by piglovesyou** [nerds-odd-e/scrummaster-checklist#30]
Please deploy the latest site source, the website is not fresh.

https://scrummasterchecklist.org/
![Screen Shot 2019-08-25 at 22 36 58](https://user-images.githubusercontent.com/217530/63650725-e1d7b280-c788-11e9-9226-be151c339abc.png)

**Comment by SabotagePerformanceAppraisals** [comment]
Yikes!  This looks very old.  I wonder how long it's been like this.  I don't have admin rights to this site, so we need Bas or someone to fix.

**Comment by SabotagePerformanceAppraisals** [comment]
resolved now

**Comment by piglovesyou** [comment]
Quick! I checked it was. I'll close this issue.

![Screen Shot 2019-08-26 at 22 58 22](https://user-images.githubusercontent.com/217530/63696132-05682f00-c855-11e9-8876-b2c6efcc7bed.png)
