### ISSUE TITLE
Live site does not match what's checked in here.  Settings issue?

### ISSUE THREAD

**Issue by SabotagePerformanceAppraisals** [nerds-odd-e/scrummaster-checklist#43]
https://scrummasterchecklist.org is missing the Romanian updates from a couple weeks ago.  The index file doesn't match and  pdf/ScrumMaster-Checklist-2022-02-08-ro.pdf doesn't seem to be online.  Anyone know what's going on?

**Comment by basvodde** [comment]
I think this is fixed now. I needed to create a new tag.

**Comment by basvodde** [comment]
Resolved, right?
